//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisableContextMenuItems {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResTranslate() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DisableContextMenuItems.ResTranslate", typeof(ResTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 A new version has been released. Press the OK button to download the new version 的本地化字符串。
        /// </summary>
        internal static string A_new_version_has_been_released__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("A new version has been released. Press the OK button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new version has been released. Would you like to download it now ? 的本地化字符串。
        /// </summary>
        internal static string A_new_version_has_been_released__Would_you_like_to_download_it_now__ {
            get {
                return ResourceManager.GetString("A new version has been released. Would you like to download it now ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new search item to project 的本地化字符串。
        /// </summary>
        internal static string Add_new_search_item_to_project {
            get {
                return ResourceManager.GetString("Add new search item to project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always 的本地化字符串。
        /// </summary>
        internal static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occured ! 的本地化字符串。
        /// </summary>
        internal static string An_error_occured__ {
            get {
                return ResourceManager.GetString("An error occured !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attendere prego 的本地化字符串。
        /// </summary>
        internal static string Attendere_prego {
            get {
                return ResourceManager.GetString("Attendere prego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Applications 的本地化字符串。
        /// </summary>
        internal static string Audio_Applications {
            get {
                return ResourceManager.GetString("Audio Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bitte warten 的本地化字符串。
        /// </summary>
        internal static string Bitte_warten {
            get {
                return ResourceManager.GetString("Bitte warten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Business Version - Licensed 的本地化字符串。
        /// </summary>
        internal static string Business_Version___Licensed {
            get {
                return ResourceManager.GetString("Business Version - Licensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change PDF Properties 的本地化字符串。
        /// </summary>
        internal static string Change_PDF_Properties {
            get {
                return ResourceManager.GetString("Change PDF Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config Screen 的本地化字符串。
        /// </summary>
        internal static string Config_Screen {
            get {
                return ResourceManager.GetString("Config Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue activated search? 的本地化字符串。
        /// </summary>
        internal static string Continue_activated_search_ {
            get {
                return ResourceManager.GetString("Continue activated search?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop Applications 的本地化字符串。
        /// </summary>
        internal static string Desktop_Applications {
            get {
                return ResourceManager.GetString("Desktop Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direct search started 的本地化字符串。
        /// </summary>
        internal static string Direct_search_started {
            get {
                return ResourceManager.GetString("Direct search started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download new version ? 的本地化字符串。
        /// </summary>
        internal static string Download_new_version__ {
            get {
                return ResourceManager.GetString("Download new version ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 4dots Project 的本地化字符串。
        /// </summary>
        internal static string Edit_4dots_Project {
            get {
                return ResourceManager.GetString("Edit 4dots Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Erroneous search 2 的本地化字符串。
        /// </summary>
        internal static string Erroneous_search_2 {
            get {
                return ResourceManager.GetString("Erroneous search 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error ! 的本地化字符串。
        /// </summary>
        internal static string Error__ {
            get {
                return ResourceManager.GetString("Error !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error. Could not run new Setup File ! 的本地化字符串。
        /// </summary>
        internal static string Error__Could_not_run_new_Setup_File__ {
            get {
                return ResourceManager.GetString("Error. Could not run new Setup File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 1 的本地化字符串。
        /// </summary>
        internal static string Error_1 {
            get {
                return ResourceManager.GetString("Error 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 12 的本地化字符串。
        /// </summary>
        internal static string Error_12 {
            get {
                return ResourceManager.GetString("Error 12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 4 的本地化字符串。
        /// </summary>
        internal static string Error_4 {
            get {
                return ResourceManager.GetString("Error 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Could not change Language ! 的本地化字符串。
        /// </summary>
        internal static string Error_Could_not_change_Language__ {
            get {
                return ResourceManager.GetString("Error Could not change Language !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error could not read Settings ! 的本地化字符串。
        /// </summary>
        internal static string Error_could_not_read_Settings__ {
            get {
                return ResourceManager.GetString("Error could not read Settings !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error could not set Settings ! 的本地化字符串。
        /// </summary>
        internal static string Error_could_not_set_Settings__ {
            get {
                return ResourceManager.GetString("Error could not set Settings !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error during search startup 的本地化字符串。
        /// </summary>
        internal static string Error_during_search_startup {
            get {
                return ResourceManager.GetString("Error during search startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Management Applications 的本地化字符串。
        /// </summary>
        internal static string File_Management_Applications {
            get {
                return ResourceManager.GetString("File Management Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphics Applications 的本地化字符串。
        /// </summary>
        internal static string Graphics_Applications {
            get {
                return ResourceManager.GetString("Graphics Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Great application to disabler Right Click Menu Items ! 的本地化字符串。
        /// </summary>
        internal static string Great_application_to_disabler_Right_Click_Menu_Items__ {
            get {
                return ResourceManager.GetString("Great application to disabler Right Click Menu Items !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import search result 的本地化字符串。
        /// </summary>
        internal static string Import_search_result {
            get {
                return ResourceManager.GetString("Import search result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Init Project 的本地化字符串。
        /// </summary>
        internal static string Init_Project {
            get {
                return ResourceManager.GetString("Init Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It is necessary to upgrade to the latest version of the application. Press the OK button to download the new version 的本地化字符串。
        /// </summary>
        internal static string It_is_necessary_to_upgrade_to_the_latest_version_of_the_application__Press_the_OK_button_to_download_the_new_version {
            get {
                return ResourceManager.GetString("It is necessary to upgrade to the latest version of the application. Press the OK" +
                        " button to download the new version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MessageTitle 的本地化字符串。
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MessageTitle7 的本地化字符串。
        /// </summary>
        internal static string MessageTitle7 {
            get {
                return ResourceManager.GetString("MessageTitle7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MessageTitle8 的本地化字符串。
        /// </summary>
        internal static string MessageTitle8 {
            get {
                return ResourceManager.GetString("MessageTitle8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On Schedule 的本地化字符串。
        /// </summary>
        internal static string On_Schedule {
            get {
                return ResourceManager.GetString("On Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation completed successfully ! 的本地化字符串。
        /// </summary>
        internal static string Operation_completed_successfully__ {
            get {
                return ResourceManager.GetString("Operation completed successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Applications 的本地化字符串。
        /// </summary>
        internal static string Other_Applications {
            get {
                return ResourceManager.GetString("Other Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password changed successfully ! 的本地化字符串。
        /// </summary>
        internal static string Password_changed_successfully__ {
            get {
                return ResourceManager.GetString("Password changed successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Recovery 的本地化字符串。
        /// </summary>
        internal static string Password_Recovery {
            get {
                return ResourceManager.GetString("Password Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password was set successfully ! 的本地化字符串。
        /// </summary>
        internal static string Password_was_set_successfully__ {
            get {
                return ResourceManager.GetString("Password was set successfully !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF Applications 的本地化字符串。
        /// </summary>
        internal static string PDF_Applications {
            get {
                return ResourceManager.GetString("PDF Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personal/EDU Version - Licensed 的本地化字符串。
        /// </summary>
        internal static string Personal_EDU_Version___Licensed {
            get {
                return ResourceManager.GetString("Personal/EDU Version - Licensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter New Password 的本地化字符串。
        /// </summary>
        internal static string Please_enter_New_Password {
            get {
                return ResourceManager.GetString("Please enter New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please wait 的本地化字符串。
        /// </summary>
        internal static string Please_wait {
            get {
                return ResourceManager.GetString("Please wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Por favor aguarde 的本地化字符串。
        /// </summary>
        internal static string Por_favor_aguarde {
            get {
                return ResourceManager.GetString("Por favor aguarde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Por favor espere 的本地化字符串。
        /// </summary>
        internal static string Por_favor_espere {
            get {
                return ResourceManager.GetString("Por favor espere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace string process started 的本地化字符串。
        /// </summary>
        internal static string Replace_string_process_started {
            get {
                return ResourceManager.GetString("Replace string process started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search duration process 的本地化字符串。
        /// </summary>
        internal static string Search_duration_process {
            get {
                return ResourceManager.GetString("Search duration process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Utilities 的本地化字符串。
        /// </summary>
        internal static string System_Utilities {
            get {
                return ResourceManager.GetString("System Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application will now exit and run the updated setup file 的本地化字符串。
        /// </summary>
        internal static string The_application_will_now_exit_and_run_the_updated_setup_file {
            get {
                return ResourceManager.GetString("The application will now exit and run the updated setup file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The New Password and the Confirm New Password Values are different ! 的本地化字符串。
        /// </summary>
        internal static string The_New_Password_and_the_Confirm_New_Password_Values_are_different__ {
            get {
                return ResourceManager.GetString("The New Password and the Confirm New Password Values are different !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is the latest version ! 的本地化字符串。
        /// </summary>
        internal static string This_is_the_latest_version__ {
            get {
                return ResourceManager.GetString("This is the latest version !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trial Version - Unlicensed 的本地化字符串。
        /// </summary>
        internal static string Trial_Version___Unlicensed {
            get {
                return ResourceManager.GetString("Trial Version - Unlicensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uniform process 的本地化字符串。
        /// </summary>
        internal static string Uniform_process {
            get {
                return ResourceManager.GetString("Uniform process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unspecified Error 的本地化字符串。
        /// </summary>
        internal static string Unspecified_Error {
            get {
                return ResourceManager.GetString("Unspecified Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Veuillez patienter 的本地化字符串。
        /// </summary>
        internal static string Veuillez_patienter {
            get {
                return ResourceManager.GetString("Veuillez patienter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Video Applications 的本地化字符串。
        /// </summary>
        internal static string Video_Applications {
            get {
                return ResourceManager.GetString("Video Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Webdesign Applications 的本地化字符串。
        /// </summary>
        internal static string Webdesign_Applications {
            get {
                return ResourceManager.GetString("Webdesign Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong Password ! 的本地化字符串。
        /// </summary>
        internal static string Wrong_Password__ {
            get {
                return ResourceManager.GetString("Wrong Password !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have entered a wrong Old Password ! 的本地化字符串。
        /// </summary>
        internal static string You_have_entered_a_wrong_Old_Password__ {
            get {
                return ResourceManager.GetString("You have entered a wrong Old Password !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your trial period of the application has expired ! Please Click on the Buy Button to Buy the Application ! 的本地化字符串。
        /// </summary>
        internal static string Your_trial_period_of_the_application_has_expired___Please_Click_on_the_Buy_Button_to_Buy_the_Application__ {
            get {
                return ResourceManager.GetString("Your trial period of the application has expired ! Please Click on the Buy Button" +
                        " to Buy the Application !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Αλλαγή Ονόματος 的本地化字符串。
        /// </summary>
        internal static string Αλλαγή_Ονόματος {
            get {
                return ResourceManager.GetString("Αλλαγή Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Αλλαγή στοιχείων εικόνας 的本地化字符串。
        /// </summary>
        internal static string Αλλαγή_στοιχείων_εικόνας {
            get {
                return ResourceManager.GetString("Αλλαγή στοιχείων εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Αλλαγή Φίλτρου Εικόνας 的本地化字符串。
        /// </summary>
        internal static string Αλλαγή_Φίλτρου_Εικόνας {
            get {
                return ResourceManager.GetString("Αλλαγή Φίλτρου Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ανανέωση Εικόνας 的本地化字符串。
        /// </summary>
        internal static string Ανανέωση_Εικόνας {
            get {
                return ResourceManager.GetString("Ανανέωση Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Εισαγωγή Εικόνας 的本地化字符串。
        /// </summary>
        internal static string Εισαγωγή_Εικόνας {
            get {
                return ResourceManager.GetString("Εισαγωγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Εναλλαγή Εικόνας 的本地化字符串。
        /// </summary>
        internal static string Εναλλαγή_Εικόνας {
            get {
                return ResourceManager.GetString("Εναλλαγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Καθορισμός Ονόματος 的本地化字符串。
        /// </summary>
        internal static string Καθορισμός_Ονόματος {
            get {
                return ResourceManager.GetString("Καθορισμός Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Μορφοποίηση Εικόνας 的本地化字符串。
        /// </summary>
        internal static string Μορφοποίηση_Εικόνας {
            get {
                return ResourceManager.GetString("Μορφοποίηση Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Νέα Εικόνα 的本地化字符串。
        /// </summary>
        internal static string Νέα_Εικόνα {
            get {
                return ResourceManager.GetString("Νέα Εικόνα", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Παράμετροι Μετρήσεως Εικόνας 的本地化字符串。
        /// </summary>
        internal static string Παράμετροι_Μετρήσεως_Εικόνας {
            get {
                return ResourceManager.GetString("Παράμετροι Μετρήσεως Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Περιγραφή Ονόματος 的本地化字符串。
        /// </summary>
        internal static string Περιγραφή_Ονόματος {
            get {
                return ResourceManager.GetString("Περιγραφή Ονόματος", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Πηγή Εικόνας 的本地化字符串。
        /// </summary>
        internal static string Πηγή_Εικόνας {
            get {
                return ResourceManager.GetString("Πηγή Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Προβολή Εικόνας 1 的本地化字符串。
        /// </summary>
        internal static string Προβολή_Εικόνας_1 {
            get {
                return ResourceManager.GetString("Προβολή Εικόνας 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Προβολή Εικόνων 的本地化字符串。
        /// </summary>
        internal static string Προβολή_Εικόνων {
            get {
                return ResourceManager.GetString("Προβολή Εικόνων", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Σφάλμα 120 的本地化字符串。
        /// </summary>
        internal static string Σφάλμα_120 {
            get {
                return ResourceManager.GetString("Σφάλμα 120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Σφάλμα 1201 的本地化字符串。
        /// </summary>
        internal static string Σφάλμα_1201 {
            get {
                return ResourceManager.GetString("Σφάλμα 1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Υπολογισμός Επιφάνειας 的本地化字符串。
        /// </summary>
        internal static string Υπολογισμός_Επιφάνειας {
            get {
                return ResourceManager.GetString("Υπολογισμός Επιφάνειας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Φίλτρο Εικόνας 的本地化字符串。
        /// </summary>
        internal static string Φίλτρο_Εικόνας {
            get {
                return ResourceManager.GetString("Φίλτρο Εικόνας", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Пожалуйста подождите 的本地化字符串。
        /// </summary>
        internal static string Пожалуйста_подождите {
            get {
                return ResourceManager.GetString("Пожалуйста подождите", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 しばらくお待ちください 的本地化字符串。
        /// </summary>
        internal static string しばらくお待ちください {
            get {
                return ResourceManager.GetString("しばらくお待ちください", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍后 的本地化字符串。
        /// </summary>
        internal static string 请稍后 {
            get {
                return ResourceManager.GetString("请稍后", resourceCulture);
            }
        }
    }
}
